image: adnrv/opencv

stages:
  - flow 

flow:
  stage: flow
  script:
  - pip install -U torch
  - pip install -U torchvision
  - mkdir output
  - cd src; python flowpp.py
  artifacts:
    paths:
      - output

report:
  image: adnrv/texlive:full
  stage: flow
  script:
    - cd report
    - latexmk -pdf -pdflatex="pdflatex --shell-escape %O %S" report 
    - mv report.pdf ../
  artifacts:
    paths:
      - report.pdf

